```{r}
library(tidyverse)
library(gprofiler2)
library(dplyr)
library(ggplot2)
library(WGCNA)
library(limma)
load("eigengenes_spearman_5_sexchr.Rdata")
load("sex_comp_combat_adj_pheno.RData")
load("log_PFAS_pheno.Rdata")
load("annotation_file.RData")
```


```{r data-cleaning}
#("G-155","G-157") are not in the pfas data 
#removing ID G-174 because it is not matching correctly with male sex
# "G-247" "G-316" "G-411" are not in pheno data but in pfas data 
exclude_ids <- c("G-155","G-157", "G-247", "G-316", "G-411", "G-174")
pheno_150 <- pheno_150[!pheno_150$participant_id %in% exclude_ids, ]
rownames(pheno_150) <- pheno_150$participant_id
sex_comp_combat.adj <- sex_comp_combat.adj[, !colnames(sex_comp_combat.adj) %in% exclude_ids]
log_pfas = log_pfas[!rownames(log_pfas) %in% exclude_ids,]

combat.adj = t(sex_comp_combat.adj)
#rownames(combat.adj) == rownames(log_pfas) TRUE ! 

#PC
pc <- prcomp(combat.adj)$x
pheno_150$PC1 = pc[,"PC1"]

#remove dashes from PFAS names 
log_pfas <- log_pfas %>%
  rename_with(~ str_replace_all(.x, "-", "_"))   # "L-PFOA" -> "L_PFOA"

# Append PFAS values to phenotype data
pfas_vars <- c("L_PFOA","PFHxS","PFNA","PFDA","s_PFOS")
pheno_150 <- cbind(pheno_150, log_pfas[, pfas_vars])

#subsetting 
eigengenes = module_Eigengenes$eigengenes
eigengenes = eigengenes[(rownames(eigengenes) %in% rownames(log_pfas)),]
```


## The variable gwg_kg (gestational weight gain) was in a separate dataset. Adding it to pheno dataset. 

```{r adding-gwg_kg}
load("~/Desktop/ViCTER_maternal_environment_2024-05-29.RData")
weight =  wide_pfas_modeling %>% 
          filter(id %in% pheno_150$participant_id) %>%
          dplyr::select(id, gwg_kg) %>%
          rename(participant_id = id)


pheno_150= merge(pheno_150, weight, by = "participant_id")
rm(list = ls()[!ls() %in% c("pheno_150", "eigengenes", "gene_color", "combat.adj","gene_info" )])
```


```{r}
Y_genes = gene_info %>% filter(.$seqnames == "Y") %>% pull(gene_name)
X_genes =  gene_info %>% filter(.$seqnames == "X") %>% pull(gene_name)
#remove X and Y genes
#combat.adj = combat.adj[,colnames(combat.adj) %in% c(Y_genes, X_genes)]
combat.adj_X = combat.adj[which(pheno_150$childs_sex == "Female"), (colnames(combat.adj) %in% X_genes)]

combat.adj_XY = combat.adj[,colnames(combat.adj) %in% c(Y_genes, X_genes)]


pheno_150[74,"gwg_kg"] = mean(pheno_150$gwg_kg, na.rm = T)
pheno_150[74, "MomBMI_36wks"] = mean(pheno_150$MomBMI_36wks, na.rm = T)
```

```{r}
design_pfas <- model.matrix(~L_PFOA + mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  childs_sex + official_enroll_category+ PC1 + delivery_method, pheno_150)
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
L_PFOA = topTable(lmboot, coef=2, confint=TRUE, number=ncol(combat.adj))

design_pfas <- model.matrix(~PFHxS+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  childs_sex + official_enroll_category+ PC1 + delivery_method, pheno_150)
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
PFHxS = topTable(lmboot, coef=2, confint=TRUE, number=ncol(combat.adj))

design_pfas <- model.matrix(~PFNA + mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  childs_sex + official_enroll_category+ PC1 + delivery_method, pheno_150)
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
PFNA = topTable(lmboot, coef=2, confint=TRUE, number=ncol(combat.adj))

design_pfas <- model.matrix(~PFDA + mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  childs_sex + official_enroll_category+ PC1 + delivery_method, pheno_150)
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
PFDA = topTable(lmboot, coef=2, confint=TRUE, number=ncol(combat.adj))

design_pfas <- model.matrix(~s_PFOS + mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  childs_sex + official_enroll_category+ PC1 + delivery_method, pheno_150)
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
s_PFOS = topTable(lmboot, coef=2, confint=TRUE, number=ncol(combat.adj))
```

```{r}
library(readxl)
lightgreen_genes <- read_excel("WGCNA_Color_List.xlsx", sheet = "lightgreen")

PFNA[lightgreen_genes$color, ]
```


```{r}
# Create a list of data frames
my_data_frames <- list(L_PFOA = L_PFOA, PFHxS = PFHxS, PFNA = PFNA, PFDA = PFDA, s_PFOS = s_PFOS)

# Using a for loop
    for (name in names(my_data_frames)) {
      file_name <- paste0(name, "_diff_expres.csv")
      write.csv(my_data_frames[[name]], file = file_name, row.names = FALSE)
    }

    # Alternatively, using mapply (more concise for this task)
    # mapply(write.csv, my_data_frames, file = paste0(names(my_data_frames), ".csv"), MoreArgs = list(row.names = FALSE))
```



```{r}
design_pfas <- model.matrix(~L_PFOA+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ PC1 + delivery_method, pheno_150[which(pheno_150$childs_sex == "Female"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_X),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)


design_pfas <- model.matrix(~PFHxS+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ delivery_method + PC1, pheno_150[which(pheno_150$childs_sex == "Female"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_X),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)

design_pfas <- model.matrix(~PFNA+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ delivery_method + PC1, pheno_150[which(pheno_150$childs_sex == "Female"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_X),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)

design_pfas <- model.matrix(~PFDA+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ delivery_method+ PC1, pheno_150[which(pheno_150$childs_sex == "Female"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_X),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)

design_pfas <- model.matrix(~s_PFOS+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ delivery_method +  PC1, pheno_150[which(pheno_150$childs_sex == "Female"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_X),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)
```



```{r}
design_pfas <- model.matrix(~PFOA+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ pc_data, pheno_150[which(pheno_150$childs_sex == "Male"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_XY[which(pheno_150$childs_sex == "Male"),]),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)


design_pfas <- model.matrix(~PFHxS+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ pc_data, pheno_150[which(pheno_150$childs_sex == "Male"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_XY[which(pheno_150$childs_sex == "Male"),]),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)


design_pfas <- model.matrix(~PFNA+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ pc_data, pheno_150[which(pheno_150$childs_sex == "Male"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_XY[which(pheno_150$childs_sex == "Male"),]),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)

design_pfas <- model.matrix(~PFDA+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ pc_data, pheno_150[which(pheno_150$childs_sex == "Male"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_XY[which(pheno_150$childs_sex == "Male"),]),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)

design_pfas <- model.matrix(~PFOS+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ pc_data, pheno_150[which(pheno_150$childs_sex == "Male"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_XY[which(pheno_150$childs_sex == "Male"),]),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
topTable(lmboot, coef=2) %>% filter(adj.P.Val < 0.05)
```

```{r}
design_pfas <- model.matrix(~PFNA+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ pc_data, pheno_150[which(pheno_150$childs_sex == "Female"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_X),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
PFNA = topTable(lmboot, coef=2, number = 15012 )
PFNA$gene_name = rownames(PFNA)
plot1 <- ggplot(data = PFNA, aes(x = logFC , y= -log10(P.Value))) +
  geom_point(data = subset(PFNA, adj.P.Val <= 0.05), aes(color = "Associated with PFNA"), size = 2) +
  geom_point(data = subset(PFNA, adj.P.Val > 0.05), aes(color = "Not Significant"), size = 2) +
  scale_color_manual(values = c("Associated with PFNA" = "purple", "Not Significant" = "grey")) +
  labs(
       x = "Coefficient Estimate",
       y = "-log10(p-value)",
       color = "q-value < 0.05") + geom_label_repel(data = subset(PFNA, adj.P.Val<= 0.05), aes(label = gene_name),
                            box.padding   = 0.5, 
                            segment.color = 'grey50') +  scale_x_continuous(limits = c(-1, 1), breaks= seq(-1, 1, 0.25)) + theme(legend.position="bottom")
```

```{r}
design_pfas <- model.matrix(~PFOS+ mom_age_at_birth + mom_education + gest_age_in_weeks_edd + gwg_kg +  official_enroll_category+ pc_data, pheno_150[which(pheno_150$childs_sex == "Female"),])
#Linear Fit and FDR#
lmres <- lmFit(t(combat.adj_X),design_pfas)
#Boostrap standard error function
lmboot <- eBayes(lmres)
##Issue with maintaining labels in reduced subsets
PFOS = topTable(lmboot, coef=2, number = 15012 )
PFOS$gene_name = rownames(PFOS)
plot2 <- ggplot(data = PFOS, aes(x = logFC , y= -log10(P.Value))) +
  geom_point(data = subset(PFOS, adj.P.Val <= 0.05), aes(color = "Associated with PFOS"), size = 2) +
  geom_point(data = subset(PFOS, adj.P.Val > 0.05), aes(color = "Not Significant"), size = 2) +
  scale_color_manual(values = c("Associated with PFOS" = "blue", "Not Significant" = "grey")) +
  labs(
       x = "Coefficient Estimate",
       y = "-log10(p-value)",
       color = "q-value < 0.05") + geom_label_repel(data = subset(PFOS, adj.P.Val<= 0.05), aes(label = gene_name),
                            box.padding   = 0.5, 
                            segment.color = 'grey50') +  scale_x_continuous(limits = c(-1, 1), breaks= seq(-1, 1, 0.25)) + theme(legend.position="bottom")
```

```{r}
library(gridExtra)
grid.arrange(plot1, plot2, ncol=2)
```