---
title: "WGCNA_prep_subset"
output: html_document
date: '2022-10-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(WGCNA)
library(GWENA)
load("combat_adj_91_samples.Rdata")
combat.adj = t(combat.adj)
```

## 
```{r}
powers=seq(from=2,to=20,by=2) 
pst=pickSoftThreshold(combat.adj,powerVector=powers, networkType ="signed", moreNetworkConcepts=T)[[2]] 
cex1=1.1
cex.axis=1.5
cex.lab=1.5
cex.main=1.5 
par(mfrow=c(2,2));
plot(powers,-sign(pst[,3])*pst[,2],type="n",
     xlab="Soft Threshold",
     ylab="SFT,signed Rˆ2",cex.axis=cex.axis, cex.main=cex.main, cex.lab=cex.lab, main="Scale Free Fit Index Rˆ2");
text(powers,-sign(pst[,3])*pst[,2], labels=powers,cex=cex1,col="red")
# this line corresponds to using an Rˆ2 cut-off of h 
abline(h=0.95,col="red")
plot(powers,pst$Density,
     type="n", xlab="Soft Threshold",ylab="Density", cex.axis=cex.axis, cex.main=cex.main,cex.lab=cex.lab, main="Density") 
text(powers,pst$Density,labels=powers,cex=cex1,col="red") 
plot(powers,pst$Heterogeneity,type="n",xlab="Soft Threshold", ylab="Heterogeneity",cex.main=cex.main, cex.lab=cex.lab, cex.axis=cex.axis, main="Heterogeneity") 
text(powers,pst$Heterogeneity,labels=powers,cex=cex1,col="red") 
plot(powers,pst$Centralization,type="n",xlab="Soft Threshold", ylab="Centralization",cex.axis=cex.axis, cex.main=cex.main, cex.lab=cex.lab, main="Centralization") 
text(powers, pst$Centralization, labels=powers,cex=cex1, col="red")
```

## Including Plots

You can also embed plots, for example:

```{r}
powers = 1:20
#Call the network topology analysis function
#Analysis of scale free topology for multiple hard thresholds
sft = pickSoftThreshold(data = combat.adj, dataIsExpr = T, powerVector = powers,networkType ="signed", corFnc="bicor" )
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
powers = 1:20
#Call the network topology analysis function
#Analysis of scale free topology for multiple hard thresholds
sft = pickSoftThreshold(data = combat.adj, dataIsExpr = T, powerVector = powers,networkType ="signed", corFnc="cor", corOptions = list(method = "spearman"))
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
```

